### ISSUE TITLE
gtkmm-plplot install crash, while brew upgrade xmi-msim

### ISSUE THREAD

**Issue by simionovici** [tschoonj/homebrew-tap#1]
Homebrew 2.2.5; python 3.7.6.1; gcc 9.2.0.3

brew install gtkmm-plplot
==> Installing gtkmm-plplot from tschoonj/tap
==> Downloading https://github.com/tschoonj/gtkmm-plplot/releases/download/gtkmm-plplot-2.4/gtkmm-plp
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/gtkmm-plplot/2.4
==> make install
Last 15 lines from /Users/alex/Library/Logs/Homebrew/gtkmm-plplot/02.make:
char    *ctermid(char *);
         ^
char    *ctermid(char *);
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/_ctermid.h:26:10: note: previous declaration is here
char    *ctermid(char *);

1 error generated.
make[1]: *** [libgtkmm_plplot_2.0_la-plotdatasurface.lo] Error 1
make: *** [install-recursive] Error 1

**Comment by tschoonj** [comment]
Hi Alex,

Please try running: `brew gist-logs gtkmm-plplot`. If successful, it should produce a gist with the build logs: please paste gist url here.

**Comment by simionovici** [comment]
Hi Tom,
gist-logs at the end in red.
xraylib has disappeared from brew !!!

Thanks,
-a

I've deleted all xraylib and reinstalled but it only installs in conda, not
in brew, and it works in python as you suggested:
(axrf) /Users/alex-8906>python
Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:19)
[Clang 9.0.0 (tags/RELEASE_900/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from xraylib import *
>>> CS_FluorLine(38, 0, 17.5)
44.77846283033054
 *************************** xraylib doesn't exist in brew *********
(axrf) /Users/alex-8797>brew install tschoonj/tap/xraylib
Error: No available formula with the name "tschoonj/tap/xraylib"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.

**********************upgrading gtkmm-plplot********************************
(axrf) /Users/alex-8796>brew upgrade tschoonj/tap/gtkmm-plplot
Updating Homebrew...
==> Upgrading 1 outdated package:
tschoonj/tap/gtkmm-plplot 2.3 -> 2.4
==> Upgrading tschoonj/tap/gtkmm-plplot
==> Downloading
https://github.com/tschoonj/gtkmm-plplot/releases/download/gtkmm-plplot-2.4/gtkmm-plplot-2.4.tar.gz
Already downloaded:
/Users/alex/Library/Caches/Homebrew/downloads/03c1cf604001a97b8d2d08ce8f1817cb38f9ada50a6c5e68092cf8dda6565d2e--gtkmm-plplot-2.4.tar.gz
==> ./configure --disable-silent-rules
--prefix=/usr/local/Cellar/gtkmm-plplot/2.4
==> make install
Last 15 lines from /Users/alex/Library/Logs/Homebrew/gtkmm-plplot/02.make:
In file included from
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/wchar.h:90:
/usr/local/include/stdio.h:222:7: error: declaration of 'ctermid' has a
different language linkage
char    *ctermid(char *);
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/_ctermid.h:26:10:
note: previous declaration is here
char    *ctermid(char *);
         ^
/bin/sh ../libtool  --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H -I.
-I..  -I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include
-I/usr/local/Cellar/pcre/8.43/include
-I/usr/local/Cellar/glib/2.62.4/include/gio-unix-2.0
-I/usr/local/Cellar/glib/2.62.4/include
-I/usr/local/Cellar/glib/2.62.4/include/glib-2.0
-I/usr/local/Cellar/glib/2.62.4/lib/glib-2.0/include
-I/usr/local/opt/gettext/include
-I/usr/local/Cellar/atk/2.34.1/include/atk-1.0
-I/usr/local/Cellar/libsigc++@2/2.10.2/include/sigc++-2.0
-I/usr/local/Cellar/libsigc++@2/2.10.2/lib/sigc++-2.0/include
-I/usr/local/Cellar/glibmm/2.62.0/include/giomm-2.4
-I/usr/local/Cellar/glibmm/2.62.0/lib/giomm-2.4/include
-I/usr/local/Cellar/glibmm/2.62.0/include/glibmm-2.4
-I/usr/local/Cellar/glibmm/2.62.0/lib/glibmm-2.4/include
-I/usr/local/Cellar/atkmm/2.28.0_2/include/atkmm-1.6
-I/usr/local/Cellar/libpng/1.6.37/include/libpng16
-I/usr/local/Cellar/gdk-pixbuf/2.40.0/include/gdk-pixbuf-2.0
-I/usr/local/Cellar/libepoxy/1.5.4/include
-I/usr/local/opt/freetype/include/freetype2
-I/usr/local/Cellar/fontconfig/2.13.1/include
-I/usr/local/Cellar/pixman/0.38.4/include/pixman-1
-I/usr/local/Cellar/cairo/1.16.0_2/include/cairo
-I/usr/local/Cellar/fribidi/1.0.8/include/fribidi
-I/usr/local/Cellar/graphite2/1.3.13/include
-I/usr/local/Cellar/harfbuzz/2.6.4/include/harfbuzz
-I/usr/local/Cellar/pango/1.44.7/include/pango-1.0
-I/usr/local/Cellar/gtk+3/3.24.12_1/include/gtk-3.0/unix-print
-I/usr/local/Cellar/gtk+3/3.24.12_1/include/gtk-3.0
-I/usr/local/Cellar/cairomm/1.12.2_1/include/cairomm-1.0
-I/usr/local/Cellar/cairomm/1.12.2_1/lib/cairomm-1.0/include
-I/usr/local/Cellar/pangomm/2.42.0_2/include/pangomm-1.4
-I/usr/local/Cellar/pangomm/2.42.0_2/lib/pangomm-1.4/include
-I/usr/local/Cellar/gtkmm3/3.24.2/include/gtkmm-3.0
-I/usr/local/Cellar/gtkmm3/3.24.2/lib/gtkmm-3.0/include
-I/usr/local/Cellar/gtkmm3/3.24.2/include/gdkmm-3.0
-I/usr/local/Cellar/gtkmm3/3.24.2/lib/gdkmm-3.0/include
-I/usr/local/Cellar/plplot/5.15.0_1/include/plplot
-I/usr/local/Cellar/libpng/1.6.37/include/libpng16
-I/usr/local/opt/freetype/include/freetype2
-I/usr/local/Cellar/fontconfig/2.13.1/include
-I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include
-I/usr/local/Cellar/pcre/8.43/include
-I/usr/local/Cellar/glib/2.60.4_1/include
-I/usr/local/Cellar/glib/2.60.4_1/include/glib-2.0
-I/usr/local/Cellar/glib/2.60.4_1/lib/glib-2.0/include
-I/usr/local/opt/gettext/include
-I/usr/local/Cellar/pixman/0.38.4/include/pixman-1
-I/usr/local/Cellar/cairo/1.16.0_1/include/cairo
-I/usr/local/Cellar/fribidi/1.0.5/include/fribidi
-I/usr/local/Cellar/graphite2/1.3.13/include
-I/usr/local/Cellar/harfbuzz/2.5.1_1/include/harfbuzz
-I/usr/local/Cellar/pango/1.42.4_2/include/pango-1.0 -I..
 -DG_LOG_DOMAIN=\"Gtkmm::PLplot\"   -g -O2 -std=c++11 -c -o
libgtkmm_plplot_2.0_la-plotdata3d.lo `test -f 'plotdata3d.cpp' || echo
'./'`plotdata3d.cpp
1 error generated.
make[1]: *** [libgtkmm_plplot_2.0_la-utils.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
1 error generated.
make[1]: *** [libgtkmm_plplot_2.0_la-plotdatasurface.lo] Error 1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I..
-I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include
-I/usr/local/Cellar/pcre/8.43/include
-I/usr/local/Cellar/glib/2.62.4/include/gio-unix-2.0
-I/usr/local/Cellar/glib/2.62.4/include
-I/usr/local/Cellar/glib/2.62.4/include/glib-2.0
-I/usr/local/Cellar/glib/2.62.4/lib/glib-2.0/include
-I/usr/local/opt/gettext/include
-I/usr/local/Cellar/atk/2.34.1/include/atk-1.0
-I/usr/local/Cellar/libsigc++@2/2.10.2/include/sigc++-2.0
-I/usr/local/Cellar/libsigc++@2/2.10.2/lib/sigc++-2.0/include
-I/usr/local/Cellar/glibmm/2.62.0/include/giomm-2.4
-I/usr/local/Cellar/glibmm/2.62.0/lib/giomm-2.4/include
-I/usr/local/Cellar/glibmm/2.62.0/include/glibmm-2.4
-I/usr/local/Cellar/glibmm/2.62.0/lib/glibmm-2.4/include
-I/usr/local/Cellar/atkmm/2.28.0_2/include/atkmm-1.6
-I/usr/local/Cellar/libpng/1.6.37/include/libpng16
-I/usr/local/Cellar/gdk-pixbuf/2.40.0/include/gdk-pixbuf-2.0
-I/usr/local/Cellar/libepoxy/1.5.4/include
-I/usr/local/opt/freetype/include/freetype2
-I/usr/local/Cellar/fontconfig/2.13.1/include
-I/usr/local/Cellar/pixman/0.38.4/include/pixman-1
-I/usr/local/Cellar/cairo/1.16.0_2/include/cairo
-I/usr/local/Cellar/fribidi/1.0.8/include/fribidi
-I/usr/local/Cellar/graphite2/1.3.13/include
-I/usr/local/Cellar/harfbuzz/2.6.4/include/harfbuzz
-I/usr/local/Cellar/pango/1.44.7/include/pango-1.0
-I/usr/local/Cellar/gtk+3/3.24.12_1/include/gtk-3.0/unix-print
-I/usr/local/Cellar/gtk+3/3.24.12_1/include/gtk-3.0
-I/usr/local/Cellar/cairomm/1.12.2_1/include/cairomm-1.0
-I/usr/local/Cellar/cairomm/1.12.2_1/lib/cairomm-1.0/include
-I/usr/local/Cellar/pangomm/2.42.0_2/include/pangomm-1.4
-I/usr/local/Cellar/pangomm/2.42.0_2/lib/pangomm-1.4/include
-I/usr/local/Cellar/gtkmm3/3.24.2/include/gtkmm-3.0
-I/usr/local/Cellar/gtkmm3/3.24.2/lib/gtkmm-3.0/include
-I/usr/local/Cellar/gtkmm3/3.24.2/include/gdkmm-3.0
-I/usr/local/Cellar/gtkmm3/3.24.2/lib/gdkmm-3.0/include
-I/usr/local/Cellar/plplot/5.15.0_1/include/plplot
-I/usr/local/Cellar/libpng/1.6.37/include/libpng16
-I/usr/local/opt/freetype/include/freetype2
-I/usr/local/Cellar/fontconfig/2.13.1/include
-I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include
-I/usr/local/Cellar/pcre/8.43/include
-I/usr/local/Cellar/glib/2.60.4_1/include
-I/usr/local/Cellar/glib/2.60.4_1/include/glib-2.0
-I/usr/local/Cellar/glib/2.60.4_1/lib/glib-2.0/include
-I/usr/local/opt/gettext/include
-I/usr/local/Cellar/pixman/0.38.4/include/pixman-1
-I/usr/local/Cellar/cairo/1.16.0_1/include/cairo
-I/usr/local/Cellar/fribidi/1.0.5/include/fribidi
-I/usr/local/Cellar/graphite2/1.3.13/include
-I/usr/local/Cellar/harfbuzz/2.5.1_1/include/harfbuzz
-I/usr/local/Cellar/pango/1.42.4_2/include/pango-1.0 -I..
-DG_LOG_DOMAIN=\"Gtkmm::PLplot\" -g -O2 -std=c++11 -c plotdata3d.cpp
 -fno-common -DPIC -o .libs/libgtkmm_plplot_2.0_la-plotdata3d.o
make: *** [install-recursive] Error 1

If reporting this issue please do so at (not Homebrew/brew or
Homebrew/core):
  https://github.com/tschoonj/homebrew-tap/issues

These open issues may also help:
gtkmm-plplot install crash, while brew upgrade xmi-msim
https://github.com/tschoonj/homebrew-tap/issues/1

==> Checking for dependents of upgraded formulae...
==> Upgrading 1 dependent:
tschoonj/tap/xmi-msim 7.0_1 -> 8.0
Error: No available formula with the name "xraylib" (dependency of
tschoonj/tap/xmi-msim)
***********************xmi-msim upgrade* **********************
(axrf) /Users/alex-8797>brew upgrade  tschoonj/tap/xmi-msim
==> Upgrading 1 outdated package:
tschoonj/tap/xmi-msim 7.0_1 -> 8.0
Error: No available formula with the name "xraylib" (dependency of
tschoonj/tap/xmi-msim)

*********************upgrade xrmc* ***********************************
(axrf) /Users/alex-8798>brew upgrade  tschoonj/tap/xrmc
Warning: tschoonj/tap/xrmc 6.7.0 already installed
********** *gist-logs for gtkmm-plplot****************
(axrf) /Users/alex-8926>brew gist-logs gtkmm-plplot


*https://gist.github.com/ef2ec7682eee96d9e17cfaafb806c149
<https://gist.github.com/ef2ec7682eee96d9e17cfaafb806c149>*

>

**Comment by tschoonj** [comment]
Alex, based on your `brew doctor` output alone I would strongly recommend to completely delete everything inside your /usr/local directory and install Homebrew from scratch... And after doing so: please resist the temptation to install anything in there manually: this folder should really be exclusively used by Homebrew.
